# version: "3.9"

# services:
#   frontend:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: tvk-frontend-prod
#     ports:
#       - "8080:80"
#     restart: unless-stopped
#     depends_on:
#       - frontend-dev

#   frontend-dev:
#     image: node:20
#     container_name: tvk-frontend-dev
#     working_dir: /app
#     volumes:
#       - .:/app
#       - /app/node_modules
#     command: sh -c "npm install && npm run dev"
#     ports:
#       - "5174:5173"
#     restart: unless-stopped

###################################################################
## production ##

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: tvk-frontend:latest
    container_name: tvk-frontend-prod
    ports:
      - "8080:80"
    restart: unless-stopped
